apiVersion: v1
kind: ConfigMap 
metadata:
  name: web-config 
data:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "database-1.cluster-c8b4yi0mqdjc.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
