deployment:
  name: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: skdockerhub2012/my-attendance-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecretName: docker-creds

dockerRegistrySecret: AgCtW14DwD64IjsTyU7x8wUN4iispH1HLuAdkh282aPRiltaHi3x3c2dS4am4XoFHHQvf5x9/Utivx1dyrEG305FfWKrvBZzd0lXNF4Jrbpqs9VTvuD8OGE76TH3BXRUWrrczzwa/n8LQPfIUE6H6nzWOlvfDaolNr4PvylrCjqyAk1QgI/ylGxsHTUFtfeHOXpVSW9HMTeVLCCUNNBH0ynMCs3zFHD2xXzF4TV7vkVVa73jM+Z0L5ymnaWrQ9G/qaEPTyFext9w5evffoh5U/9d5Ki9zFsjBORCjDvSDgVtQJN61UsyxJBdueSSgrBwhz49vqOOpVr+kOHUU0p0BW7jAlaY1vTs41iCdRDFntoaxzat7bIyywSecJ0RgbVJ4fg7h310W6MOef8eWigJbqJN58OEAGG4xAkjCDu4z2Nt5O0z9nByk+f2k+LX9JLoKsiyXdljXg6CcoxSJImaBadUF8I3lgMfblAXdUpoLOaI3PViURuRTItYv4qP99LT+FcYKusrLR0zgxY4XoSwWjt9pxa80CxCvV+G6THjRoFqnZ6kg7WAdIpCW1OoYgw8azNiYikx5tcLzo0KnslO9I0vIWC8c4ycfgYVXScQ7aYGrgyO4ibuPFcZWHf7v0ZbPnTcTpALt0fZFGSYwJ5M4tuNIw+LpmFh1RbDzeMFMmtt1yPd386B2XXUh3e3pbvJEtxH64rrowD8AAvywcR/K2/PGwxZQtzNk5U1xVzi9Nf+dFVUfXPp/k7QSuchXMob//AOFtl50zxT98/WsALbBFQF8CArK+ips6aus3m7dVjA9XSIRyeYsm8RymH9tAd4gxI1ELgnGbOSkpHhOMTSmfHvfGbO53hOEXU3WExeQXtPA2N1Slj+Ne70dJR4HzuyGzZe4QCZNYyrazGj6syLJrilPXKxLtW8YVlvVqE3T9GF0Ywb

# Project namespace for your application
namespace: attendance-app

dbSecretName: db-secrets

dbUser: AgAwCSwQAF4ZzmIZjmwQMtNDSCUYevWFWxzXm8fEdX03x78qYbRre27tXArC3/LRR29x8qnA9yq9pxs9GHVNubcjVHMbZuqB7cKdGxNSkqjB/qpqmqD1z0dizjnh9ABaZrRGD2iaqt7EaiAELANL5sxjhAPwfUKJH15yqlC6JoNxXotxw3zOcu5fAhv6fPjlVkk8cDcaq129PMK6wbPYFSBAnwJ0ZijwOG+gjVzqZMYAMXFqRzJbmMZPWuIWs767yRlJmPJ9ZP+Pl1C5Lb5R5ewvU1WWRqcnPfSEhJmPj/f2flIuVVrhaxA/xTCvXwfUESgyIe+rZkQi7YCA3kUvL6tW0imRrSvpmd40tf3ERrcDR725xI6e773zVdv8CBzUFhNRJ5K+HdqtlSLQpFf30V0tOwr9QtiWJ127OO5SWI6LNFr1F89VS1xgIXxxxJejalRIGt2B+FIXoLghkg/Eb5Vl3yKKv+IXF9sZuKuSgoUsPx9ke6OMtEk4Y5hJOEYRaJoebqPMCaqY5vBsJlT5HmbjamOvK7X6/ClBRGD2ZJ9fvjE8MvaZDXhXfVTQAaSN92N5JNOdak+q60NZsPBm5wV5qOgXBqll6NyvyPIDtekOc+O3al8FbxnASPbhINE1eqCVr5voGMC4aJQOTuRL/uXbh4isdpqYcI9obnvPyJ5BPLQco0A9P7q5Ko2o64TiQF7T/RCE8mDqIg==
dbPassword: AgB/wVJBq6+ZuIESmS1AmG8JVPWpqees51SCKcvAoozxMqQM8FH9ya2LAx/j0ZiR+x3qdzK/2c7CPUFbTLM/l/e+ED3UoLQ+cm2dvxNOWlnnQI/3vdNX4BRC5DCqfyjFawYyhZlXd3XupWVeIUk+WCcxYIGNmpc5tcXMgwUF2f3rSemGMLFuqI+/1xAVCB7Lxp0u0H1foO80gH9JHrSG7NcLzbyLrCGjsI6ov+/5PR6EW/5d0GULfx7fNWmcuWbnQxAI12Qpi9f2o66MNPmPgSWXUw+0OxJNcllbf8b2dZKpeBIXmiHi1sl0I3mpilQLrErvG7nDAjYlMCeHs7D9PihCJbQ6Y0uUmRMgqCkPGV2HeeNKFrwTPNaSpUGvG2NrEDO2j4cIpkjkvMDEg40qAUnFaWaMlnDpWQxa9BAqLfNZIRq86TFP6lSZTvV4pgvHB7KAAAvZr6GqjcYdyAsPxJeqSH1dnFef21N++4XVICeguW5zddwUVU6Helwlq6aOwa3eXT6AsOpKiiQsXQmtWxRqvvgLmJdTCe570up5hMGxtZq/nuJU3I0MAenDEX5K0S8xiME2TNyxWtsgw2RgBWFV9wNMRB9P8XsRCBn55lqhFfg7X+a8G8vnnPpjJaG/68KfE2acVcs8TwKyv+nSN9n2svuFfShdWP3+hxK7KDKQ+1pXjrbiRHjHVn4ek9ly0zvAwHWC7JzEyA==

config:
  name: db-config
  DB_HOST: DB_HOST: database-1.cluster-c8b4yi0mqdjc.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app


